"""WHO country indicators, per-market subgroup rates, overlap flags

Two new catalogues and two flags.

`disease_subgroups.is_overlapping` defaults to false, which is the correct
backfill: every subgroup written before this migration belonged to a
hierarchical partition that summed to 1, and false is exactly what that was.
`is_default_population` defaults to false for the same reason — none of those
rows stood for the whole population.
WHO country indicators, per-market subgroup rates, overlap flags

Revision ID: 5622a3993aaf
Revises: a67e571d206f
Create Date: 2026-08-26 17:20:07.394697
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5622a3993aaf'
down_revision: str | None = 'a67e571d206f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_health_indicators',
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.CHAR(length=3), nullable=False),
    sa.Column('indicator', sa.Text(), nullable=False),
    sa.Column('indicator_kind', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('vintage_year', sa.SmallInteger(), nullable=True),
    sa.Column('confidence_tier', sa.CHAR(length=1), nullable=False),
    sa.CheckConstraint('value IS NULL OR (value >= 0 AND value <= 1)', name='ck_country_health_indicators_fraction'),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ),
    sa.PrimaryKeyConstraint('indicator_id'),
    sa.UniqueConstraint('country_code', 'indicator', name='uq_country_health_indicators_natural')
    )
    op.create_table('subgroup_country_rates',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('subgroup_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.CHAR(length=3), nullable=False),
    sa.Column('share_of_diagnosed', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('eligible_factor', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence_tier', sa.CHAR(length=1), nullable=False),
    sa.CheckConstraint('eligible_factor > 0 AND eligible_factor <= 1', name='ck_subgroup_country_rates_eligible'),
    sa.CheckConstraint('share_of_diagnosed > 0 AND share_of_diagnosed <= 1', name='ck_subgroup_country_rates_share'),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ),
    sa.ForeignKeyConstraint(['subgroup_id'], ['disease_subgroups.subgroup_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rate_id'),
    sa.UniqueConstraint('subgroup_id', 'country_code', name='uq_subgroup_country_rates_natural')
    )
    op.add_column(
        'disease_subgroups',
        sa.Column(
            'is_default_population', sa.Boolean(), nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        'disease_subgroups',
        sa.Column(
            'is_overlapping', sa.Boolean(), nullable=False, server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disease_subgroups', 'is_overlapping')
    op.drop_column('disease_subgroups', 'is_default_population')
    op.drop_table('subgroup_country_rates')
    op.drop_table('country_health_indicators')
    # ### end Alembic commands ###
