"""outcomes, subgroups and payer perspective for M16-M18

Five catalogues and three scenario columns.

`scenarios.perspective` is added with a server default of `health_system`
rather than as a nullable column. Every scenario written before this migration
was, in effect, computed from a health-system perspective — the denominator
was the national population, because there was no other — so backfilling that
value states what those runs already assumed. A NULL would claim they had no
perspective, which is not the same thing and would make every historical run
un-quotable as PMPM.

Revision ID: a67e571d206f
Revises: e0b1295f0fae
Create Date: 2026-08-26
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a67e571d206f'
down_revision: str | None = 'e0b1295f0fae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_subgroups',
    sa.Column('subgroup_id', sa.Integer(), nullable=False),
    sa.Column('indication_id', sa.Integer(), nullable=False),
    sa.Column('subgroup_code', sa.Text(), nullable=False),
    sa.Column('subgroup_label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('share_of_diagnosed', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('eligible_factor', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('uptake_multiplier', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('confidence_tier', sa.CHAR(length=1), nullable=False),
    sa.CheckConstraint('eligible_factor > 0 AND eligible_factor <= 1', name='ck_disease_subgroups_eligible'),
    sa.CheckConstraint('share_of_diagnosed > 0 AND share_of_diagnosed <= 1', name='ck_disease_subgroups_share'),
    sa.CheckConstraint('uptake_multiplier > 0', name='ck_disease_subgroups_uptake'),
    sa.ForeignKeyConstraint(['indication_id'], ['indications.indication_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subgroup_id'),
    sa.UniqueConstraint('indication_id', 'subgroup_code', name='uq_disease_subgroups_natural')
    )
    op.create_table('event_costs',
    sa.Column('event_cost_id', sa.Integer(), nullable=False),
    sa.Column('event_class', sa.Text(), nullable=False),
    sa.Column('country_code', sa.CHAR(length=3), nullable=False),
    sa.Column('unit_cost_local', sa.Numeric(), nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=False),
    sa.Column('cost_year', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('confidence_tier', sa.CHAR(length=1), nullable=False),
    sa.CheckConstraint('unit_cost_local >= 0', name='ck_event_costs_non_negative'),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ),
    sa.PrimaryKeyConstraint('event_cost_id'),
    sa.UniqueConstraint('event_class', 'country_code', name='uq_event_costs_natural')
    )
    op.create_table('response_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Text(), nullable=False),
    sa.Column('responder_share', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('responder_low', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('responder_high', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('mean_weight_loss_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('regain_per_year', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('trial', sa.Text(), nullable=False),
    sa.Column('nct_id', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('vintage_year', sa.SmallInteger(), nullable=True),
    sa.Column('confidence_tier', sa.CHAR(length=1), nullable=False),
    sa.CheckConstraint('regain_per_year >= 0 AND regain_per_year <= 1', name='ck_response_profiles_regain'),
    sa.CheckConstraint('responder_share >= 0 AND responder_share <= 1', name='ck_response_profiles_share'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.drug_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('drug_id', 'threshold', name='uq_response_profiles_natural')
    )
    op.create_table('subgroup_event_rates',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('subgroup_id', sa.Integer(), nullable=False),
    sa.Column('event_class', sa.Text(), nullable=False),
    sa.Column('baseline_annual_rate', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('rate_low', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('rate_high', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('vintage_year', sa.SmallInteger(), nullable=True),
    sa.Column('confidence_tier', sa.CHAR(length=1), nullable=False),
    sa.CheckConstraint('baseline_annual_rate >= 0 AND baseline_annual_rate <= 1', name='ck_subgroup_event_rates_range'),
    sa.ForeignKeyConstraint(['subgroup_id'], ['disease_subgroups.subgroup_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rate_id'),
    sa.UniqueConstraint('subgroup_id', 'event_class', name='uq_subgroup_event_rates_natural')
    )
    op.create_table('treatment_effects',
    sa.Column('effect_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('event_class', sa.Text(), nullable=False),
    sa.Column('relative_reduction', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('reduction_low', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('reduction_high', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('observed_in_subgroup', sa.Text(), nullable=True),
    sa.Column('trial', sa.Text(), nullable=False),
    sa.Column('nct_id', sa.Text(), nullable=True),
    sa.Column('follow_up_weeks', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('vintage_year', sa.SmallInteger(), nullable=True),
    sa.Column('confidence_tier', sa.CHAR(length=1), nullable=False),
    sa.CheckConstraint('relative_reduction >= 0 AND relative_reduction < 1', name='ck_treatment_effects_range'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.drug_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('effect_id'),
    sa.UniqueConstraint('drug_id', 'event_class', name='uq_treatment_effects_natural')
    )
    op.add_column(
        'scenarios',
        sa.Column(
            'perspective', sa.Text(), nullable=False, server_default='health_system',
        ),
    )
    op.add_column('scenarios', sa.Column('covered_population', sa.BigInteger(), nullable=True))
    op.add_column('scenarios', sa.Column('subgroup_codes', sa.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.create_check_constraint('ck_scenarios_covered_population', 'scenarios', 'covered_population IS NULL OR covered_population > 0')
    op.create_check_constraint('ck_scenarios_perspective', 'scenarios', "perspective IN ('insurer', 'employer', 'government', 'health_system')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_scenarios_perspective', 'scenarios', type_='check')
    op.drop_constraint('ck_scenarios_covered_population', 'scenarios', type_='check')
    op.drop_column('scenarios', 'subgroup_codes')
    op.drop_column('scenarios', 'covered_population')
    op.drop_column('scenarios', 'perspective')
    op.drop_table('treatment_effects')
    op.drop_table('subgroup_event_rates')
    op.drop_table('response_profiles')
    op.drop_table('event_costs')
    op.drop_table('disease_subgroups')
    # ### end Alembic commands ###
