"""initial schema

Revision ID: bae9187702f7
Revises: 
Create Date: 2026-08-23 19:38:40.837066
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'bae9187702f7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The `vector` type must exist before guideline_chunks.embedding is
    # created. pgvector is not a trusted extension, so on a fresh database a
    # superuser must have run this already (see docs/DATABASE.md); the call
    # is a privilege-free no-op once the extension is present.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_code', sa.CHAR(length=3), nullable=False),
    sa.Column('country_name', sa.Text(), nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('health_system_type', sa.Text(), nullable=True),
    sa.Column('adult_share', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('adult_share_source', sa.Text(), nullable=False),
    sa.Column('adult_share_confidence_tier', sa.CHAR(length=1), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('adult_share > 0.5 AND adult_share < 0.95', name='ck_countries_adult_share_range'),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=False),
    sa.Column('rate_per_usd', sa.Numeric(), nullable=False),
    sa.Column('fetched_date', sa.Date(), nullable=False),
    sa.CheckConstraint('rate_per_usd > 0', name='ck_fx_rates_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_code', 'fetched_date', name='uq_fx_rates_natural')
    )
    op.create_index('idx_fx_rates_lookup', 'fx_rates', ['currency_code', 'fetched_date'], unique=False)
    op.create_table('guideline_documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('issuing_body', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('publication_year', sa.SmallInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('title', 'issuing_body', name='uq_guideline_documents_natural')
    )
    op.create_table('indications',
    sa.Column('indication_id', sa.Integer(), nullable=False),
    sa.Column('indication_name', sa.Text(), nullable=False),
    sa.Column('therapy_area', sa.Text(), nullable=False),
    sa.Column('icd10', sa.Text(), nullable=True),
    sa.Column('who_indicator_code', sa.Text(), nullable=True),
    sa.Column('default_horizon', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('indication_id'),
    sa.UniqueConstraint('indication_name')
    )
    op.create_table('staging_extracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'row_index', name='uq_staging_extracts_natural')
    )
    op.create_index('idx_staging_extracts_source', 'staging_extracts', ['source_id', 'fetched_at'], unique=False)
    op.create_table('country_economics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.CHAR(length=3), nullable=False),
    sa.Column('indicator', sa.Text(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence_tier', sa.CHAR(length=1), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'indicator', 'year', name='uq_country_economics_natural')
    )
    op.create_table('drugs',
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.Text(), nullable=False),
    sa.Column('generic_name', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('drug_class', sa.Text(), nullable=True),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('indication_id', sa.Integer(), nullable=True),
    sa.Column('is_comparator', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['indication_id'], ['indications.indication_id'], ),
    sa.PrimaryKeyConstraint('drug_id'),
    sa.UniqueConstraint('drug_name', name='uq_drugs_name')
    )
    op.create_table('eligibility_criteria',
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('indication_id', sa.Integer(), nullable=False),
    sa.Column('criterion_code', sa.Text(), nullable=False),
    sa.Column('criterion_label', sa.Text(), nullable=False),
    sa.Column('criterion_type', sa.Text(), nullable=False),
    sa.Column('default_factor', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('factor_low', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('factor_high', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence_tier', sa.CHAR(length=1), nullable=False),
    sa.Column('correlated_with', sa.ARRAY(sa.Text()), nullable=True),
    sa.CheckConstraint('default_factor > 0 AND default_factor <= 1', name='ck_eligibility_criteria_factor'),
    sa.ForeignKeyConstraint(['indication_id'], ['indications.indication_id'], ),
    sa.PrimaryKeyConstraint('criterion_id'),
    sa.UniqueConstraint('indication_id', 'criterion_code', name='uq_eligibility_criteria_natural')
    )
    op.create_table('epidemiology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.CHAR(length=3), nullable=False),
    sa.Column('indication_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('prevalence_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('prevalence_low', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('prevalence_high', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('age_group', sa.Text(), nullable=False),
    sa.Column('sex', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence_tier', sa.CHAR(length=1), nullable=False),
    sa.Column('is_projected', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(prevalence_low IS NULL OR prevalence_low <= prevalence_pct) AND (prevalence_high IS NULL OR prevalence_high >= prevalence_pct)', name='ck_epidemiology_interval_ordered'),
    sa.CheckConstraint('prevalence_pct > 0 AND prevalence_pct < 100', name='ck_epidemiology_prevalence_range'),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ),
    sa.ForeignKeyConstraint(['indication_id'], ['indications.indication_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'indication_id', 'year', 'age_group', 'sex', name='uq_epidemiology_natural')
    )
    op.create_table('funnel_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indication_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.CHAR(length=3), nullable=True),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('value_low', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('value_high', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence_tier', sa.CHAR(length=1), nullable=False),
    sa.CheckConstraint('value > 0 AND value <= 1', name='ck_funnel_defaults_rate'),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ),
    sa.ForeignKeyConstraint(['indication_id'], ['indications.indication_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indication_id', 'country_code', 'stage', name='uq_funnel_defaults_natural')
    )
    op.create_table('guideline_chunks',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['guideline_documents.document_id'], ),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_guideline_chunks_natural')
    )
    op.create_index('idx_guideline_embedding', 'guideline_chunks', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
    op.create_table('scenarios',
    sa.Column('scenario_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('indication_id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.Text(), nullable=False),
    sa.Column('asset_class', sa.Text(), nullable=True),
    sa.Column('development_stage', sa.Text(), nullable=True),
    sa.Column('launch_year', sa.SmallInteger(), nullable=False),
    sa.Column('horizon_years', sa.SmallInteger(), nullable=False),
    sa.Column('reporting_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('country_codes', sa.ARRAY(sa.CHAR(length=3)), nullable=False),
    sa.Column('parent_scenario_id', sa.UUID(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cardinality(country_codes) > 0', name='ck_scenarios_has_market'),
    sa.CheckConstraint('horizon_years BETWEEN 1 AND 5', name='ck_scenarios_horizon_range'),
    sa.ForeignKeyConstraint(['indication_id'], ['indications.indication_id'], ),
    sa.ForeignKeyConstraint(['parent_scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_table('drug_prices',
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.CHAR(length=3), nullable=False),
    sa.Column('price_local', sa.Numeric(), nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=False),
    sa.Column('price_basis', sa.Text(), nullable=False),
    sa.Column('annual_cost_usd', sa.Numeric(), nullable=True),
    sa.Column('gross_to_net_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('confidence_tier', sa.CHAR(length=1), nullable=False),
    sa.CheckConstraint("price_basis <> 'estimated_net' OR gross_to_net_pct IS NOT NULL", name='ck_drug_prices_net_requires_ratio'),
    sa.CheckConstraint('gross_to_net_pct IS NULL OR (gross_to_net_pct > 0 AND gross_to_net_pct <= 1)', name='ck_drug_prices_gross_to_net'),
    sa.CheckConstraint('price_local > 0', name='ck_drug_prices_positive'),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.drug_id'], ),
    sa.PrimaryKeyConstraint('price_id'),
    sa.UniqueConstraint('drug_id', 'country_code', 'price_basis', name='uq_drug_prices_natural')
    )
    op.create_table('drug_regimens',
    sa.Column('regimen_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('dose_amount', sa.Numeric(), nullable=False),
    sa.Column('dose_unit', sa.Text(), nullable=False),
    sa.Column('units_per_admin', sa.Numeric(), nullable=False),
    sa.Column('admins_per_year', sa.Numeric(), nullable=False),
    sa.Column('wastage_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('persistence_12m', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence_tier', sa.CHAR(length=1), nullable=False),
    sa.CheckConstraint('persistence_12m > 0 AND persistence_12m <= 1', name='ck_drug_regimens_persistence'),
    sa.CheckConstraint('wastage_pct >= 0 AND wastage_pct < 1', name='ck_drug_regimens_wastage'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.drug_id'], ),
    sa.PrimaryKeyConstraint('regimen_id'),
    sa.UniqueConstraint('drug_id', name='uq_drug_regimens_drug')
    )
    op.create_table('model_runs',
    sa.Column('run_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('engine_version', sa.Text(), nullable=False),
    sa.Column('run_type', sa.Text(), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fx_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("run_type IN ('forward', 'reverse', 'owsa', 'psa')", name='ck_model_runs_type'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_model_runs_scenario', 'model_runs', ['scenario_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('scenario_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.CHAR(length=3), nullable=True),
    sa.Column('parameter_path', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'country_code', 'parameter_path', name='uq_scenario_overrides_natural')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # The `vector` extension is intentionally left in place. It is
    # database-level infrastructure that this migration does not own, and
    # dropping it fails for any role that is not its owner.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_overrides')
    op.drop_index('idx_model_runs_scenario', table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_table('drug_regimens')
    op.drop_table('drug_prices')
    op.drop_table('scenarios')
    op.drop_index('idx_guideline_embedding', table_name='guideline_chunks', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
    op.drop_table('guideline_chunks')
    op.drop_table('funnel_defaults')
    op.drop_table('epidemiology')
    op.drop_table('eligibility_criteria')
    op.drop_table('drugs')
    op.drop_table('country_economics')
    op.drop_index('idx_staging_extracts_source', table_name='staging_extracts')
    op.drop_table('staging_extracts')
    op.drop_table('indications')
    op.drop_table('guideline_documents')
    op.drop_index('idx_fx_rates_lookup', table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_table('countries')
    # ### end Alembic commands ###
